Neos:
  Neos:
    fusion:
      autoInclude:
        'Alan.NeosLogin': true
  Fusion:
    defaultContext:
      Alan.AlanCaptchaHelper: 'Alan\NeosLogin\Eel\AlanCaptchaHelper'

  Flow:
    http:
      middlewares:
        'alanLogin':
          position: 'after securityEntryPoint'
          middleware: 'Alan\NeosLogin\Middleware\AlanLoginMiddleware'

Alan:
  NeosLogin:
    active: true
    apiKey: 'API_KEY'
    siteKey: 'SITE_KEY'
    monitorTag: 'MONITOR_TAG (optional)'
    lang:
      unverifiedtext: 'Unverified'
      verifiedtext: 'Verified'
      retrytext: 'Retry'
      workingtext: 'Working...'
      starttext: 'Start'

